### ISSUE TITLE
make introprog.PixelWindow handle Delet key in clear text

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog-scalalib#1]
Delete key is now a special utf charcter displayed as  or \utf(007F). Make lastKey be "Delete"

**Comment by elliotbrack** [comment]
This also goes for the arrow keys, enter key, tab, and so on on OS X. Is that out of scope for the project? I imagine you'd want some sort of Map[String, String] for all the special characters, or handle all the special cases by their keycode.

The root cause is Java special handling on OS X to make ⌘ et al display correctly, so I imagine you could extract the lookup table from that.
