### ISSUE TITLE
implement JFrame.setTitle in PixelWindow

### ISSUE THREAD

**Issue by ke8683da** [lunduniversity/introprog-scalalib#8]
I am requesting the setTitle method to be implemented and accessible from introprog.PixelWindow. I noticed that JFrame has a method for renaming the frame title, and I am missing this feature in PixelWindow, it could be useful

**Comment by bjornregnell** [comment]
Implemented by https://github.com/lunduniversity/introprog-scalalib/commit/cf2aee56bf3d10538fbc511d77cba31f378853bc

**Comment by bjornregnell** [comment]
I reopening this issue as I just noticed that the `frame.setTitle` in the merged PR is not executed on the Swing thread. @ke8683da Could you fix this by sending a new PR with `Swing { frame.setTitle(title) }` block similar to  `def show()` and then test this **thoroughly** using existing labs with game loops running for a while with some load on your CPU such as in Snake, so that we can spot any threading issues make e.g. the Swing thread hang.

**Comment by ke8683da** [comment]
PR sent, tested on Linux and Windows, working flawlessly. [Demo](https://gyazo.com/b0663c72679b014787acebb9ffb10bb5)

**Comment by bjornregnell** [comment]
merged; thanks!
